### ISSUE TITLE
Duplicate?

### ISSUE THREAD

**Issue by dglaude** [BlitzCityDIY/Adafruit_CircuitPython_Wii_Classic#1]
Could you please consider https://github.com/jfurcean/CircuitPython_WiiChuck ?

That was added to the Community Bundle on February 2021:
https://github.com/adafruit/CircuitPython_Community_Bundle/commit/6a027bc80a6f889457ec1f2c7355a2cd041e1fc1

**Comment by tekktrik** [comment]
^ @BlitzCityDIY

**Comment by BlitzCityDIY** [comment]
hihi- anything in the adafruit bundle requires adafruit support and the team does not have all of the peripherals to be able to troubleshoot/support issues that folks could have whereas the classic controllers and nunchucks are more common
